//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int Status { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> DeliveryMan_ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> AdminNotification_Id { get; set; }
    
        public virtual AdminNotification AdminNotification { get; set; }
        public virtual DeliveryMan DeliveryMan { get; set; }
        public virtual User User { get; set; }
    }
}
