//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer_Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offer_Products()
        {
            this.Order_Items = new HashSet<Order_Items>();
        }
    
        public int Id { get; set; }
        public int Offer_Id { get; set; }
        public int Product_Id { get; set; }
        public double DiscountedPrice { get; set; }
        public int DiscountPercentage { get; set; }
        public double SlashPrice { get; set; }
        public string ImageUrl { get; set; }
        public bool IsDeleted { get; set; }
        public string Description { get; set; }
    
        public virtual Offer Offer { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Items> Order_Items { get; set; }
    }
}
