//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Items
    {
        public int Id { get; set; }
        public int Qty { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> Package_Id { get; set; }
        public int StoreOrder_Id { get; set; }
        public Nullable<int> Offer_Product_Id { get; set; }
        public Nullable<int> Offer_Package_Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
    
        public virtual Offer_Packages Offer_Packages { get; set; }
        public virtual Offer_Products Offer_Products { get; set; }
        public virtual Package Package { get; set; }
        public virtual Product Product { get; set; }
        public virtual StoreOrder StoreOrder { get; set; }
    }
}
