//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPayment
    {
        public int Id { get; set; }
        public string Amount { get; set; }
        public string PaymentType { get; set; }
        public string CashCollected { get; set; }
        public string Status { get; set; }
        public string Order_Id { get; set; }
        public string AccountNo { get; set; }
        public Nullable<int> DeliveryMan_Id { get; set; }
        public int Application_Id { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual DeliveryMan DeliveryMan { get; set; }
        public virtual Order Order { get; set; }
    }
}
