//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.StoreOrders = new HashSet<StoreOrder>();
        }
    
        public int Id { get; set; }
        public string OrderNo { get; set; }
        public int Status { get; set; }
        public System.DateTime OrderDateTime { get; set; }
        public System.DateTime DeliveryTime_From { get; set; }
        public System.DateTime DeliveryTime_To { get; set; }
        public string AdditionalNote { get; set; }
        public int PaymentMethod { get; set; }
        public double Subtotal { get; set; }
        public double ServiceFee { get; set; }
        public double DeliveryFee { get; set; }
        public double Total { get; set; }
        public int User_ID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> OrderPayment_Id { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<int> DeliveryMan_Id { get; set; }
        public bool RemoveFromDelivererHistory { get; set; }
        public short PaymentStatus { get; set; }
        public bool RemoveFromUserHistory { get; set; }
    
        public virtual DeliveryMan DeliveryMan { get; set; }
        public virtual OrderPayment OrderPayment { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreOrder> StoreOrders { get; set; }
    }
}
