//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public double DeliveryFee { get; set; }
        public string Currency { get; set; }
        public double MinimumOrderPrice { get; set; }
        public string StandardWorkingHours { get; set; }
        public string AboutUs { get; set; }
        public string Help { get; set; }
        public double ServiceFee { get; set; }
        public double NearByRadius { get; set; }
    }
}
