//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreRating
    {
        public int Id { get; set; }
        public int User_Id { get; set; }
        public int Store_Id { get; set; }
        public int Rating { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual User User { get; set; }
    }
}
