//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreDeliveryHour
    {
        public System.TimeSpan Monday_From { get; set; }
        public System.TimeSpan Monday_To { get; set; }
        public System.TimeSpan Tuesday_From { get; set; }
        public System.TimeSpan Tuesday_To { get; set; }
        public System.TimeSpan Wednesday_From { get; set; }
        public System.TimeSpan Wednesday_To { get; set; }
        public System.TimeSpan Thursday_From { get; set; }
        public System.TimeSpan Thursday_To { get; set; }
        public System.TimeSpan Friday_From { get; set; }
        public System.TimeSpan Friday_To { get; set; }
        public System.TimeSpan Saturday_From { get; set; }
        public System.TimeSpan Saturday_To { get; set; }
        public System.TimeSpan Sunday_From { get; set; }
        public System.TimeSpan Sunday_To { get; set; }
        public int Id { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
