//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDevice
    {
        public int Id { get; set; }
        public string DeviceName { get; set; }
        public string UDID { get; set; }
        public bool Platform { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string AuthToken { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> DeliveryMan_Id { get; set; }
    
        public virtual DeliveryMan DeliveryMan { get; set; }
        public virtual User User { get; set; }
    }
}
