//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddress
    {
        public int Id { get; set; }
        public int User_ID { get; set; }
        public short Type { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string StreetName { get; set; }
        public string Floor { get; set; }
        public string Apartment { get; set; }
        public string NearestLandmark { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsPrimary { get; set; }
        public string BuildingName { get; set; }
    
        public virtual User User { get; set; }
    }
}
